### ISSUE TITLE
Exclude Admin group

### ISSUE THREAD

**Issue by ArchBlood** [cuzy-app/humhub-modules-group-membership#1]
From testing this module, it allows users to not only add themselves to any group that is listed, but also allows users to add themselves to the admin group as well, this shouldn't be possible and could cause issues if you have this group displayed on the directory
![Screenshot_4](https://user-images.githubusercontent.com/35392110/102296966-6faa5480-3f1c-11eb-8812-edd22c0a0c18.png)

**Comment by marc-farre** [comment]
Thanks for your contribution!
Sure, `UsersManageTheirMembership` should not extend `humhub\modules\admin\components\BaseAdminPermission` as it is only for admin group.
