### ISSUE TITLE
Idea: description text specification

### ISSUE THREAD

**Issue by uab22** [cuzy-app/humhub-modules-group-membership#4]
Hello! The description of this module, has me wondering what the module actually does. The reason for this, is I assume groups are to begin with all about people being able to join 'themselves'. Because I am new to HumHub, someone like me could be helped to comprehend what the module does, if a sentence is included about how HumHub groups work without this module. Thanks

**Comment by marc-farre** [comment]
Groups are similar to "Roles" on others platforms. It enables to give specific permissions to users, classify your users in sub-communities, etc.
With Humhub, only admin can add a user to a group.
This module enables users to add themselves to one or more groups (the admin can define which groups are allowed to be auto-added by users).

**Comment by uab22** [comment]
Thank you for explaining! Now I comprehend that you are talking about an entirely different type of group, the Guests, Users, Moderators and Administrator groups/roles. Or that is what I think. You see, what I originally thought, is that you meant 'group' in a competely different sense. 

My installation happens to have been set to Norwegian, and I haven't checked what it's called in English, but if we consider Facebook, you may know that there you have something called 'pages' and something called 'groups'. Those are not, then, roles but the kind of 'place', so where users can talk in a 'subforum'. I assume both things are not called 'groups' in HumHub, as this might be even more confusing than I originally thought. Thanks, again!

**Comment by marc-farre** [comment]
Facebook groups are equivalent to Humhub spaces.
And on Humhub, you have global groups (that you can edit in Administration -> Users -> Groups) and space's groups (that you can see in the spaces' members or permissions.
This module is for the global groups.
