### ISSUE TITLE
group membership

### ISSUE THREAD

**Issue by bck-beep** [cuzy-app/humhub-modules-group-membership#5]
I have added the mod, and in permission of i set so members can join or leave themselves, but when go to the created group there is no button to join the group,,it has the invite button, but non to actually join? should I uninstall the group mod and re install or is there something I'm missing, there is no configure button in the mod section for this mod, just setting, permissions , deactivate and uninstall in the dropdown? hope it isnt an issue just something simple... and another question,, where would a member find a place to start their own groups if any, cant find anywhere, or can only admin start groups, be nice if members could start own groups for others to join...thanks in advance..

screenshots included..
![Screenshot 2024-02-08 112906](https://github.com/cuzy-app/humhub-modules-group-membership/assets/159047237/1e2e4ea7-dbc5-4edf-88c6-35335619c32c)
![Screenshot 2024-02-08 113033](https://github.com/cuzy-app/humhub-modules-group-membership/assets/159047237/80438c5d-6e56-475c-8275-211266539e74)
![Screenshot 2024-02-08 113138](https://github.com/cuzy-app/humhub-modules-group-membership/assets/159047237/ab95f00c-1c92-4f19-8793-6dee0f632e41)

**Comment by marc-farre** [comment]
Users must go here to add themselves to an allowed group:

![image](https://github.com/cuzy-app/humhub-modules-group-membership/assets/23310825/48664429-e0a0-4121-a116-84edcfa570c6)

**Comment by bck-beep** [comment]
ok,,is there a setting for members to start thier own groups, ? and when members go to people, click droppdown for groups, go to a group, should there be a button there to join or do they have to go to profile, settings to my groups to see and join groups? again i do appreciate this, sorry if I'm  a pain..

**Comment by marc-farre** [comment]
> ok,,is there a setting for members to start thier own groups, ? and when members go to people, click droppdown for groups, go to a group, should there be a button there to join or do they have to go to profile, settings to my groups to see and join groups? again i do appreciate this, sorry if I'm a pain..

Sorry, but this is not possible with this module.

But as it's Open Source, if you have coding knowledge, you can suggest a code to add this feature to the module.

**Comment by bck-beep** [comment]
went to the my groups, join one as regular member, but if click on it after join, it does not bring me to the group, no way to post, comment etc ?am i missing a setting or something?

**Comment by bck-beep** [comment]
so members cant comment or post, ask questions or anything etc in a group,
and/or cant start their own either? if cant participate in a group almost
pointless to have one? or am i misunderstanding..

**Comment by bck-beep** [comment]
i understand not being able to start own group, but should be able to post
in one started by admin? hope I'm understanding you correctly?

**Comment by marc-farre** [comment]
About your message:

> i just dont understand once member joins a group, there is no way to participate, post, comment or anything..is there a way to set this that i missed?  even as admin only lets put group and description of it, but no interaction within the group, so i figured i missed a setting or something, did i?

I think you are making a confusion between Groups and Spaces. Groups are only to give rights to users and a few other things:
![image](https://github.com/cuzy-app/humhub-modules-group-membership/assets/23310825/ffe83cd3-e3c2-4f53-a454-f74bf88e50bf)

Only admins can manage groups in Administration -> Users -> Groups

**Comment by marc-farre** [comment]
> no way to post, comment etc ?

No. You need Spaces for that.
See https://docs.humhub.org/docs/about/humhub#users--groups

**Comment by bck-beep** [comment]
Thanks for the tip!
